### ISSUE TITLE
player fell out of the world

### ISSUE THREAD

**Issue by ghost** [matanrak/AdvanceRespawn#1]
config
Spectate_Respawn: true
Spectate_Respawn_Delay: 15

ss
![2017-02-03_16 10 45](https://cloud.githubusercontent.com/assets/5884000/22596387/a71ea7ee-ea2b-11e6-83eb-c544dc4f10bb.png)
![2017-02-03_16 10 49](https://cloud.githubusercontent.com/assets/5884000/22596393/a9b91c46-ea2b-11e6-8181-41f6eaa711f1.png)
![2017-02-03_16 13 33](https://cloud.githubusercontent.com/assets/5884000/22596415/c1a261dc-ea2b-11e6-9940-0a009a25493a.png)

it gives the player a spectator mode : O

**Comment by matanrak** [comment]
The GitHub code is out dated btw,
And yes it gives spectator mode but you still can't teleport while using it.

**Comment by matanrak** [comment]
Or is thing a bug?
Did the player receive Spector mode after respawning?

**Comment by ghost** [comment]
"Did the player receive Spector mode after respawning?"
yes

"The GitHub code is out dated btw,"
Change the link, pls.

**Comment by matanrak** [comment]
Oo forgot to update sorry, 
The problem is fixed, like wayyy back.
Sorry );
